import { Component } from '@angular/core';
import '../../dxf_viewer_module/dist/js/index.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  public addGroup(data: any) {
    console.log('new group contains: ', data.detail[0]);
  }

  public addDevice(data: any) {
    console.log('new devices contains: ', data.detail[0]);
  }


  public floors = JSON.stringify([
    {
      id: 1,
      floor_layer_name: 'XREF',
      fixture_layer_name: 'EL63101-_LICHT-ARM',
      sensor_layer_name: 'EL63101-_LICHT-ARM',
      full_name: 'Basement 1',
      position: 4,
      project_id: 2,
      building_id: 4,
      download_url: 'https://portal-api.summa.systems/api/v1/files/46/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MTAxNzI1OTQsInN1YiI6IjEyNyJ9.V7MCMP-TbuWKk6nAx8coAoUMzXYVIt65k4UnxQ2kw2s',
    },
    {
      id: 2,
      floor_layer_name: 'XREF',
      fixture_layer_name: 'EL63101-_LICHT-ARM',
      sensor_layer_name: 'EL63101-_LICHT-ARM',
      full_name: 'Basement',
      position: 3,
      project_id: 2,
      building_id: 1,
      download_url:
        'https://portal-api.summa.systems/api/v1/files/149/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MTAxNzI1OTQsInN1YiI6IjEyNyJ9.V7MCMP-TbuWKk6nAx8coAoUMzXYVIt65k4UnxQ2kw2s',
    },
    {
      id: 10,
      floor_layer_name: 'XREF',
      fixture_layer_name: '',
      sensor_layer_name: 'EL63101-_LICHT-ARM',
      full_name: 'Tz',
      position: 2,
      project_id: 2,
      building_id: 4,
      download_url:
        'https://portal-api.summa.systems/api/v1/files/239/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MTUwMTczODYsInN1YiI6Ijg3In0.RXeXWIGt-ax7npoqPGjvqYb1ynuvmNH0KP3uM8z6Rrk',
    },
    {
      id: 8,
      floor_layer_name: '',
      fixture_layer_name: '',
      sensor_layer_name: '',
      full_name: 'Floor 1',
      position: 1,
      project_id: 2,
      building_id: 4,
      download_url:
        'https://portal-api.summa.systems/api/v1/files/160/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MTAxNzI1OTQsInN1YiI6IjEyNyJ9.V7MCMP-TbuWKk6nAx8coAoUMzXYVIt65k4UnxQ2kw2s',
    },
  ]);

  public devices = JSON.stringify([
    {
      id: 5098,
      x: '56286',
      y: '23089',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'daytonopaal',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5099,
      x: '56286',
      y: '25489',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'daytonopaal',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5100,
      x: '54486',
      y: '23089',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'daytonopaal',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5101,
      x: '54486',
      y: '25489',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'daytonopaal',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5102,
      x: '47778',
      y: '24687',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Cobra 1760',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5103,
      x: '47778',
      y: '23962',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Cobra 1760',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5104,
      x: '49579',
      y: '24687',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Cobra 1760',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5105,
      x: '49579',
      y: '23962',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Cobra 1760',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5106,
      x: '49946',
      y: '23605',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5107,
      x: '50326',
      y: '24818',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5108,
      x: '49434',
      y: '25005',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5109,
      x: '47804',
      y: '24148',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5110,
      x: '48344',
      y: '25005',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5111,
      x: '50751',
      y: '25516',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Sita',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5112,
      x: '50751',
      y: '25162',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Sita',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5113,
      x: '51042',
      y: '25399',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Sita',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
    },
    {
      id: 5098,
      x: '56286',
      y: '23089',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'daytonopaal',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5099,
      x: '56286',
      y: '25489',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'daytonopaal',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5100,
      x: '54486',
      y: '23089',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'daytonopaal',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5101,
      x: '54486',
      y: '25489',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'daytonopaal',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5102,
      x: '47778',
      y: '24687',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Cobra 1760',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5103,
      x: '47778',
      y: '23962',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Cobra 1760',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5104,
      x: '49579',
      y: '24687',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Cobra 1760',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5105,
      x: '49579',
      y: '23962',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Cobra 1760',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5106,
      x: '49946',
      y: '23605',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5107,
      x: '50326',
      y: '24818',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5108,
      x: '49434',
      y: '25005',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5109,
      x: '47804',
      y: '24148',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5110,
      x: '48344',
      y: '25005',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Seizo 95',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5111,
      x: '50751',
      y: '25516',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Sita',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5112,
      x: '50751',
      y: '25162',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Sita',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 5113,
      x: '51042',
      y: '25399',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Sita',
      mac_address: null,
      status: true,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22206,
      x: '3713',
      y: '16974',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22207,
      x: '3713',
      y: '16359',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22208,
      x: '3713',
      y: '16619',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22209,
      x: '3713',
      y: '13706',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22210,
      x: '3713',
      y: '13350',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22211,
      x: '3713',
      y: '11027',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22212,
      x: '3713',
      y: '10672',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22213,
      x: '3713',
      y: '8039',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22214,
      x: '3713',
      y: '7423',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22215,
      x: '3713',
      y: '7683',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Mico R 80',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22216,
      x: '8685',
      y: '6661',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22217,
      x: '8685',
      y: '9061',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22218,
      x: '6885',
      y: '6661',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22219,
      x: '6885',
      y: '9061',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22220,
      x: '6873',
      y: '17157',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22221,
      x: '8673',
      y: '17157',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22222,
      x: '6873',
      y: '14757',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22223,
      x: '8673',
      y: '14757',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22224,
      x: '18956',
      y: '15275',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22225,
      x: '15956',
      y: '15275',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22226,
      x: '13544',
      y: '14748',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22227,
      x: '12551',
      y: '11206',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22228,
      x: '14371',
      y: '11206',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22229,
      x: '16190',
      y: '11206',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22230,
      x: '18010',
      y: '11206',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22231,
      x: '19830',
      y: '11206',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Fontana S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22232,
      x: '21396',
      y: '16598',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'DIMMER',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22233,
      x: '21396',
      y: '15476',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'DIMMER',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 22234,
      x: '1879',
      y: '5573',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'LED groen',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHTSUMMA',
      file_id: 10,
      rotation: 0,
    },
    {
      id: 4,
      x: '37243',
      y: '5960',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: null,
    },
    {
      id: 10,
      x: '40465',
      y: '1684',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 14,
      x: '37243',
      y: '7533',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 4,
    },
    {
      id: 7,
      x: '37283',
      y: '9134',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: [],
      mA: null,
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: null,
    },
    {
      id: 13,
      x: '40520',
      y: '5960',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: '123123123',
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: null,
    },
    {
      id: 12,
      x: '38965',
      y: '5960',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: '232323',
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: null,
    },
    {
      id: 15,
      x: '38454',
      y: '8260',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 4,
    },
    {
      id: 11,
      x: '39506.36619594553',
      y: '4018.1292191316024',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: [],
      mA: '0.0',
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 2,
    },
    {
      id: 220,
      x: '41065.61185056855',
      y: '9832.902098214821',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'New device',
      mac_address: null,
      status: false,
      serial_number: 'ttttt',
      channels: [],
      mA: null,
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: null,
    },
    {
      id: 449,
      x: '39028.04763702629',
      y: '9036.47570715079',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'New device',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: [],
      mA: null,
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: null,
    },
    {
      id: 5,
      x: '40115',
      y: '9051',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: '123123',
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 7,
    },
    {
      id: 16,
      x: '39708',
      y: '8260',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: '123ds',
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 7,
    },
    {
      id: 199,
      x: '40276.14702520929',
      y: '7512.803951557964',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Test devv',
      mac_address: null,
      status: true,
      serial_number: '12412512152',
      channels: ['ch1'],
      mA: null,
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 36,
    },
    {
      id: 2,
      x: '39387',
      y: '3005',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: null,
    },
    {
      id: 1,
      x: '37235',
      y: '1684',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: '12312',
      status: false,
      serial_number: '2424242424',
      channels: [],
      mA: null,
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 8,
      x: '40949',
      y: '4544',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: '23424234',
      channels: [],
      mA: null,
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 3,
    },
    {
      id: 6,
      x: '41033',
      y: '8260',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: true,
      serial_number: '23414214',
      channels: [],
      mA: null,
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 36,
    },
    {
      id: 3,
      x: '39626.469833534924',
      y: '5434.762944914757',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: '235456',
      channels: [],
      mA: '0.0',
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 1,
    },
    {
      id: 9,
      x: '40959.469833534924',
      y: '4879.762944914757',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: '287739921',
      channels: [],
      mA: '0.0',
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 1,
      rotation: 0,
      group_id: 2,
    },
    {
      id: 20,
      x: '37243',
      y: '5960',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 19,
      x: '39513',
      y: '5170',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: 40,
    },
    {
      id: 21,
      x: '40115',
      y: '9051',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 22,
      x: '41033',
      y: '8260',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 30,
      x: '37243',
      y: '7533',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 200,
      x: '40677.31499973793',
      y: '7208.579425263793',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'New device',
      mac_address: null,
      status: false,
      serial_number: '3521525',
      channels: ['ch2'],
      mA: null,
      ceil_height: 0,
      selected_cells: [],
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 17,
      x: '37235',
      y: '1684',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 18,
      x: '39387',
      y: '3005',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 31,
      x: '38454',
      y: '8260',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 32,
      x: '39708',
      y: '8260',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 23,
      x: '37283',
      y: '9134',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 24,
      x: '40949',
      y: '4544',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 25,
      x: '40846',
      y: '4615',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 26,
      x: '40465',
      y: '1684',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 27,
      x: '39535',
      y: '3005',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
    {
      id: 28,
      x: '38965',
      y: '5960',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: 40,
    },
    {
      id: 29,
      x: '40520',
      y: '5960',
      width: '0',
      height: '0',
      type: 'fixture',
      block_name: 'Dea Carmenta S',
      mac_address: null,
      status: false,
      serial_number: null,
      channels: null,
      mA: null,
      ceil_height: 0,
      selected_cells: null,
      angle: 0,
      layer: 'EL63101-_LICHT-ARM',
      file_id: 2,
      rotation: 0,
      group_id: null,
    },
  ]);

  public groups = JSON.stringify([
    {
      id: 46,
      name: 'Tz group 1',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 10,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [],
      group_ids: [],
      positions: [
        {
          x: '5000',
          y: '16974',
        },
      ],
    },
    {
      id: 2,
      name: 'Group 1',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 1,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [9, 11],
      group_ids: [],
      positions: [
        {
          x: '40054.80372469752',
          y: '6760.3168628915755',
        },
      ],
    },
    {
      id: 30,
      name: 'Group 10',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 2,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [],
      group_ids: [40, 39],
      positions: [
        {
          x: '49239.0',
          y: '20000.0',
        },
      ],
    },
    {
      id: 39,
      name: 'Group 20',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 2,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [],
      group_ids: [],
      positions: [
        {
          x: null,
          y: null,
        },
      ],
    },
    {
      id: 38,
      name: 'Group 3',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 12,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [188, 190],
      group_ids: [],
      positions: [
        {
          x: '48889.0',
          y: '25005.0',
        },
      ],
    },
    {
      id: 40,
      name: 'Group 30',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 2,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [19, 28],
      group_ids: [],
      positions: [
        {
          x: '59239.0',
          y: '30065.0',
        },
      ],
    },
    {
      id: 7,
      name: 'Group 4',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 1,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [16, 5],
      group_ids: [],
      positions: [
        {
          x: '39911.5',
          y: '8655.5',
        },
      ],
    },
    {
      id: 6,
      name: 'Group Children',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 1,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [],
      group_ids: [],
      positions: [
        {
          x: null,
          y: null,
        },
      ],
    },
    {
      id: 5,
      name: 'Group Children 3',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 1,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [],
      group_ids: [],
      positions: [
        {
          x: null,
          y: null,
        },
      ],
    },
    {
      id: 8,
      name: 'Group Independence',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: null,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [],
      group_ids: [],
      positions: [
        {
          x: null,
          y: null,
        },
      ],
    },
    {
      id: 4,
      name: 'Group Parent 1',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 1,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [14, 15],
      group_ids: [6],
      positions: [
        {
          x: '38156.428717904644',
          y: '6758.380804900996',
        },
      ],
    },
    {
      id: 36,
      name: 'New Group',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: true,
      scene_id: 829,
      file_id: 1,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [6, 199],
      group_ids: [],
      positions: [
        {
          x: '40276.14702520929',
          y: '7512.803951557964',
        },
      ],
    },
    {
      id: 3,
      name: 'Root Group',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 1,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [8],
      group_ids: [4, 5, 7],
      positions: [
        {
          x: '36868.80986011129',
          y: '4143.524047536016',
        },
      ],
    },
    {
      id: 1,
      name: 'Root Group 5',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: 1,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [3],
      group_ids: [2],
      positions: [
        {
          x: '38031.25835999189',
          y: '8065.219948542874',
        },
      ],
    },
    {
      id: 12,
      name: 'Summa portal',
      x_color: 0,
      y_color: 0,
      color_type: 'cct',
      type: 'Group',
      is_active: false,
      scene_status: false,
      scene_id: 829,
      file_id: null,
      light: 0,
      color: '7F2C0A',
      intensity: 0,
      device_ids: [],
      group_ids: [],
      positions: [
        {
          x: null,
          y: null,
        },
      ],
    },
  ]);

}
