import { Component } from '@angular/core';
import '../../dxf_viewer_module/dist/js/index.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  public msg = "Xin chao ban";

  public floors = JSON.stringify([
    {
      id: 1,
      floor_layer_name: 'XREF',
      fixture_layer_name: 'EL63101-_LICHT-ARM',
      sensor_layer_name: 'EL63101-_LICHT-ARM',
      full_name: 'Basement 1',
      position: 5,
      project_id: 2,
      building_id: 4,
      download_url: 'https://portal-api.summa.systems/api/v1/files/46/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MTAxNzI1OTQsInN1YiI6IjEyNyJ9.V7MCMP-TbuWKk6nAx8coAoUMzXYVIt65k4UnxQ2kw2s'
    },
    {
      id: 2,
      floor_layer_name: 'XREF',
      fixture_layer_name: 'EL63101-_LICHT-ARM',
      sensor_layer_name: 'EL63101-_LICHT-ARM',
      full_name: 'Basement',
      position: 3,
      project_id: 2,
      building_id: 1,
      download_url: 'https://portal-api.summa.systems/api/v1/files/149/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MTAxNzI1OTQsInN1YiI6IjEyNyJ9.V7MCMP-TbuWKk6nAx8coAoUMzXYVIt65k4UnxQ2kw2s'
    },
    {
      id: 7,
      floor_layer_name: 'XREF',
      fixture_layer_name: '',
      sensor_layer_name: 'EL63101-_LICHT-ARM',
      full_name: 'Tz',
      position: 2,
      project_id: 2,
      building_id: 4,
      download_url: 'https://portal-api.summa.systems/api/v1/files/149/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MTAxNzI1OTQsInN1YiI6IjEyNyJ9.V7MCMP-TbuWKk6nAx8coAoUMzXYVIt65k4UnxQ2kw2s'
    },
    {
      id: 8,
      floor_layer_name: '',
      fixture_layer_name: '',
      sensor_layer_name: '',
      full_name: 'Floor 1',
      position: 1,
      project_id: 2,
      building_id: 4,
      download_url: 'https://portal-api.summa.systems/api/v1/files/160/download?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MTAxNzI1OTQsInN1YiI6IjEyNyJ9.V7MCMP-TbuWKk6nAx8coAoUMzXYVIt65k4UnxQ2kw2s'
    }
  ]);
  
    public devices = JSON.stringify([
      {
          "id": 4,
          "x": "37243",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 10,
          "x": "40465",
          "y": "1684",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 14,
          "x": "37243",
          "y": "7533",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 4
      },
      {
          "id": 7,
          "x": "37283",
          "y": "9134",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": [],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 13,
          "x": "40520",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": "123123123",
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 12,
          "x": "38965",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": "232323",
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 15,
          "x": "38454",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 4
      },
      {
          "id": 11,
          "x": "39506.36619594553",
          "y": "4018.1292191316024",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": [],
          "mA": "0.0",
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 2
      },
      {
          "id": 220,
          "x": "41065.61185056855",
          "y": "9832.902098214821",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "New device",
          "mac_address": null,
          "status": false,
          "serial_number": "ttttt",
          "channels": [],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 449,
          "x": "39028.04763702629",
          "y": "9036.47570715079",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "New device",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": [],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 5,
          "x": "40115",
          "y": "9051",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": "123123",
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 7
      },
      {
          "id": 16,
          "x": "39708",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": "123ds",
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 7
      },
      {
          "id": 199,
          "x": "40276.14702520929",
          "y": "7512.803951557964",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Test devv",
          "mac_address": null,
          "status": true,
          "serial_number": "12412512152",
          "channels": [
              "ch1"
          ],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 36
      },
      {
          "id": 2,
          "x": "39387",
          "y": "3005",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 1,
          "x": "37235",
          "y": "1684",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": "12312",
          "status": false,
          "serial_number": "2424242424",
          "channels": [],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 8,
          "x": "40949",
          "y": "4544",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": "23424234",
          "channels": [],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 3
      },
      {
          "id": 6,
          "x": "41033",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": true,
          "serial_number": "23414214",
          "channels": [],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 36
      },
      {
          "id": 3,
          "x": "39626.469833534924",
          "y": "5434.762944914757",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": "235456",
          "channels": [],
          "mA": "0.0",
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 1
      },
      {
          "id": 9,
          "x": "40959.469833534924",
          "y": "4879.762944914757",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": "287739921",
          "channels": [],
          "mA": "0.0",
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 1,
          "rotation": 0,
          "group_id": 2
      },
      {
          "id": 20,
          "x": "37243",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 19,
          "x": "39513",
          "y": "5170",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": 40
      },
      {
          "id": 21,
          "x": "40115",
          "y": "9051",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 22,
          "x": "41033",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 30,
          "x": "37243",
          "y": "7533",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 200,
          "x": "40677.31499973793",
          "y": "7208.579425263793",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "New device",
          "mac_address": null,
          "status": false,
          "serial_number": "3521525",
          "channels": [
              "ch2"
          ],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 17,
          "x": "37235",
          "y": "1684",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 18,
          "x": "39387",
          "y": "3005",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 31,
          "x": "38454",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 32,
          "x": "39708",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 23,
          "x": "37283",
          "y": "9134",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 24,
          "x": "40949",
          "y": "4544",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 25,
          "x": "40846",
          "y": "4615",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 26,
          "x": "40465",
          "y": "1684",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 27,
          "x": "39535",
          "y": "3005",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 28,
          "x": "38965",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": 40
      },
      {
          "id": 29,
          "x": "40520",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 2,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 194,
          "x": "string",
          "y": "string",
          "width": "string",
          "height": "string",
          "type": "fixture",
          "block_name": "string",
          "mac_address": "string",
          "status": false,
          "serial_number": "string",
          "channels": [
              "string"
          ],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [
              0
          ],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 196,
          "x": "string",
          "y": "string",
          "width": "string",
          "height": "string",
          "type": "fixture",
          "block_name": "string",
          "mac_address": "string",
          "status": false,
          "serial_number": "string",
          "channels": [
              "string"
          ],
          "mA": null,
          "ceil_height": 0,
          "selected_cells": [
              0
          ],
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 97,
          "x": "37235",
          "y": "1684",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 98,
          "x": "39387",
          "y": "3005",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 99,
          "x": "39513",
          "y": "5170",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 100,
          "x": "37243",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 101,
          "x": "40115",
          "y": "9051",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 102,
          "x": "41033",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 103,
          "x": "37283",
          "y": "9134",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 104,
          "x": "40949",
          "y": "4544",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 105,
          "x": "40846",
          "y": "4615",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 106,
          "x": "40465",
          "y": "1684",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 107,
          "x": "39535",
          "y": "3005",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 108,
          "x": "38965",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 109,
          "x": "40520",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 110,
          "x": "37243",
          "y": "7533",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 111,
          "x": "38454",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 112,
          "x": "39708",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 7,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 129,
          "x": "37235",
          "y": "1684",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 130,
          "x": "39387",
          "y": "3005",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 131,
          "x": "39513",
          "y": "5170",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 132,
          "x": "37243",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 133,
          "x": "40115",
          "y": "9051",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 134,
          "x": "41033",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 135,
          "x": "37283",
          "y": "9134",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 136,
          "x": "40949",
          "y": "4544",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 137,
          "x": "40846",
          "y": "4615",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 138,
          "x": "40465",
          "y": "1684",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 139,
          "x": "39535",
          "y": "3005",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 140,
          "x": "38965",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 141,
          "x": "40520",
          "y": "5960",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 142,
          "x": "37243",
          "y": "7533",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 143,
          "x": "38454",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      },
      {
          "id": 144,
          "x": "39708",
          "y": "8260",
          "width": "0",
          "height": "0",
          "type": "fixture",
          "block_name": "Dea Carmenta S",
          "mac_address": null,
          "status": false,
          "serial_number": null,
          "channels": null,
          "mA": null,
          "ceil_height": 0,
          "selected_cells": null,
          "angle": 0,
          "layer": "EL63101-_LICHT-ARM",
          "file_id": 9,
          "rotation": 0,
          "group_id": null
      }
  ]);
  
    public groups = JSON.stringify([
      {
          "id": 46,
          "name": "1 Group",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": null,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 43,
          "name": "AAAAA",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 13,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              206
          ],
          "group_ids": [],
          "positions": [
              {
                  "x": "41033.0",
                  "y": "8260.0"
              }
          ]
      },
      {
          "id": 37,
          "name": "AAAAX",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 12,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 44,
          "name": "BBBB",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 13,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              213,
              214,
              215
          ],
          "group_ids": [
              45
          ],
          "positions": [
              {
                  "x": "38881.5",
                  "y": "7110.0"
              }
          ]
      },
      {
          "id": 45,
          "name": "CCCC",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 13,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              203,
              212
          ],
          "group_ids": [],
          "positions": [
              {
                  "x": "39239.0",
                  "y": "5565.0"
              }
          ]
      },
      {
          "id": 2,
          "name": "Group 1",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 1,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              9,
              11
          ],
          "group_ids": [],
          "positions": [
              {
                  "x": "40054.80372469752",
                  "y": "6760.3168628915755"
              }
          ]
      },
      {
          "id": 34,
          "name": "Group 1",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 12,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 30,
          "name": "Group 10",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 2,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [
              40,
              39
          ],
          "positions": [
              {
                  "x": "39239.0",
                  "y": "5565.0"
              }
          ]
      },
      {
          "id": 39,
          "name": "Group 20",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 2,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 38,
          "name": "Group 3",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 12,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              188,
              190
          ],
          "group_ids": [],
          "positions": [
              {
                  "x": "48889.0",
                  "y": "25005.0"
              }
          ]
      },
      {
          "id": 40,
          "name": "Group 30",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 2,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              19,
              28
          ],
          "group_ids": [],
          "positions": [
              {
                  "x": "39239.0",
                  "y": "5565.0"
              }
          ]
      },
      {
          "id": 7,
          "name": "Group 4",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 1,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              16,
              5
          ],
          "group_ids": [],
          "positions": [
              {
                  "x": "39911.5",
                  "y": "8655.5"
              }
          ]
      },
      {
          "id": 6,
          "name": "Group Children",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 1,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 5,
          "name": "Group Children 3",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 1,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 8,
          "name": "Group Independence",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": null,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 4,
          "name": "Group Parent 1",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 1,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              14,
              15
          ],
          "group_ids": [
              6
          ],
          "positions": [
              {
                  "x": "38156.428717904644",
                  "y": "6758.380804900996"
              }
          ]
      },
      {
          "id": 47,
          "name": "haha",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": true,
          "scene_id": 829,
          "file_id": null,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 48,
          "name": "haha 1",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": null,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 36,
          "name": "New Group",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": true,
          "scene_id": 829,
          "file_id": 1,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              6,
              199
          ],
          "group_ids": [],
          "positions": [
              {
                  "x": "40276.14702520929",
                  "y": "7512.803951557964"
              }
          ]
      },
      {
          "id": 3,
          "name": "Root Group",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 1,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              8
          ],
          "group_ids": [
              4,
              5,
              7
          ],
          "positions": [
              {
                  "x": "36868.80986011129",
                  "y": "4143.524047536016"
              }
          ]
      },
      {
          "id": 1,
          "name": "Root Group 5",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 1,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              3
          ],
          "group_ids": [
              2
          ],
          "positions": [
              {
                  "x": "38031.25835999189",
                  "y": "8065.219948542874"
              }
          ]
      },
      {
          "id": 12,
          "name": "Summa portal",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": null,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 33,
          "name": "TEst",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": null,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [],
          "group_ids": [],
          "positions": [
              {
                  "x": null,
                  "y": null
              }
          ]
      },
      {
          "id": 42,
          "name": "TEst",
          "x_color": 0,
          "y_color": 0,
          "color_type": "cct",
          "type": "Group",
          "is_active": false,
          "scene_status": false,
          "scene_id": 829,
          "file_id": 13,
          "light": 0,
          "color": "7F2C0A",
          "intensity": 0,
          "device_ids": [
              216,
              205
          ],
          "group_ids": [
              43
          ],
          "positions": [
              {
                  "x": "39911.5",
                  "y": "8655.5"
              }
          ]
      }
  ]);
  

  public functiona(data: any){
    console.log("Bat emit success!")
    console.log(data);
  }

}
